require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RentalsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Rental. As you add validations to Rental, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      Rental_ID: "1",
      UIN: "123456789",
      Apparel_ID: "4",
      Checkout_Date: "04-12-2016",
      Expected_Return_Date: "04-16-2016",
      Return_Date: "04-14-2016"
    }
  }

  let(:invalid_attributes) {
    {
      Rental_ID: nil,
      UIN: nil,
      Apparel_ID: nil,
      Checkout_Date: nil,
      Expected_Return_Date: nil,
      Return_Date: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RentalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    sign_in create( :user )
  end

  describe "GET #index" do
    it "assigns all rentals as @rentals" do
      rental = Rental.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rentals)).to eq([rental])
    end
  end

  describe "GET #show" do
    it "assigns the requested rental as @rental" do
      rental = Rental.create! valid_attributes
      get :show, {:id => rental.to_param}, valid_session
      expect(assigns(:rental)).to eq(rental)
    end
  end

  describe "GET #new" do
    it "assigns a new rental as @rental" do
      get :new, {}, valid_session
      expect(assigns(:rental)).to be_a_new(Rental)
    end
  end

  describe "GET #edit" do
    it "assigns the requested rental as @rental" do
      rental = Rental.create! valid_attributes
      get :edit, {:id => rental.to_param}, valid_session
      expect(assigns(:rental)).to eq(rental)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Rental" do
        expect {
          post :create, {:rental => valid_attributes}, valid_session
        }.to change(Rental, :count).by(1)
      end

      it "assigns a newly created rental as @rental" do
        post :create, {:rental => valid_attributes}, valid_session
        expect(assigns(:rental)).to be_a(Rental)
        expect(assigns(:rental)).to be_persisted
      end

      it "redirects to the created rental" do
        post :create, {:rental => valid_attributes}, valid_session
        expect(response).to redirect_to(Rental.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved rental as @rental" do
        post :create, {:rental => invalid_attributes}, valid_session
        expect(assigns(:rental)).to be_a_new(Rental)
      end

      it "re-renders the 'new' template" do
        post :create, {:rental => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          Rental_ID: "2",
          UIN: "987654321",
          Apparel_ID: "8",
          Checkout_Date: "06-16-2016",
          Expected_Return_Date: "06-20-2016",
          Return_Date: "06-18-2016"
        }
      }

      it "updates the requested rental" do
        rental = Rental.create! valid_attributes
        put :update, {:id => rental.to_param, :rental => new_attributes}, valid_session
        rental.reload
        expect(assigns(:rental)).to eq(rental)
      end

      it "assigns the requested rental as @rental" do
        rental = Rental.create! valid_attributes
        put :update, {:id => rental.to_param, :rental => valid_attributes}, valid_session
        expect(assigns(:rental)).to eq(rental)
      end

      it "redirects to the rental" do
        rental = Rental.create! valid_attributes
        put :update, {:id => rental.to_param, :rental => valid_attributes}, valid_session
        expect(response).to redirect_to(rental)
      end
    end

    context "with invalid params" do
      it "assigns the rental as @rental" do
        rental = Rental.create! valid_attributes
        put :update, {:id => rental.to_param, :rental => invalid_attributes}, valid_session
        expect(assigns(:rental)).to eq(rental)
      end

      it "re-renders the 'edit' template" do
        rental = Rental.create! valid_attributes
        put :update, {:id => rental.to_param, :rental => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested rental" do
      rental = Rental.create! valid_attributes
      expect {
        delete :destroy, {:id => rental.to_param}, valid_session
      }.to change(Rental, :count).by(-1)
    end

    it "redirects to the rentals list" do
      rental = Rental.create! valid_attributes
      delete :destroy, {:id => rental.to_param}, valid_session
      expect(response).to redirect_to(rentals_url)
    end
  end

end
